/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : dash_system_boot
**     Processor   : MKL17Z256VFM4
**     Component   : MKL17Z256FM4
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Datasheet   : KL17P64M48SF6RM, Rev.3, Aug 2014
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-07-23, 14:39, # CodeGen: 13
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MKL17Z256FM4)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MKL17Z256FM4)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! gpio1 Auto initialization start */
  GPIO_DRV_Init(gpio1_InpConfig0,gpio1_OutConfig0);
  /*! gpio1 Auto initialization end */
  
  /*! i2cCom1 Auto initialization start */
  OSA_InstallIntHandler(I2C0_IRQn, i2cCom1_IRQHandler);
  I2C_DRV_SlaveInit(FSL_I2CCOM1, &i2cCom1_SlaveConfig0, &i2cCom1_SlaveState);
  /*! i2cCom1 Auto initialization end */
  
    /*! flash1 Auto initialization start */
    (void)FlashInit(&flash1_InitConfig0);
    /*! flash1 Auto initialization end */
  /*! spiComEZPort Auto initialization start */
  SPI_DRV_MasterInit(FSL_SPICOMEZPORT, &spiComEZPort_MasterState);
  SPI_DRV_MasterConfigureBus(FSL_SPICOMEZPORT, &spiComEZPort_MasterConfig0, &spiComEZPort_calculatedBaudRate);
  /*! spiComEZPort Auto initialization end */
  
  /*! lpuartUblox Auto initialization start */
  LPUART_DRV_Init(FSL_LPUARTUBLOX,&lpuartUblox_State,&lpuartUblox_InitConfig0);
  LPUART_DRV_InstallRxCallback(FSL_LPUARTUBLOX, lpuartUblox_RxCallback, ublox_rx, NULL, true);
  /*! lpuartUblox Auto initialization end */
}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

