/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : lpuartUblox.h
**     Project     : dash_system_boot
**     Processor   : MKL17Z256VFM4
**     Component   : fsl_lpuart
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-07-20, 22:00, # CodeGen: 11
**     Abstract    :
**
**     Contents    :
**         LPUART_DRV_Init                - lpuart_status_t LPUART_DRV_Init(uint32_t instance,lpuart_state_t *...
**         LPUART_DRV_Deinit              - lpuart_status_t LPUART_DRV_Deinit(uint32_t instance);
**         LPUART_DRV_InstallRxCallback   - lpuart_rx_callback_t LPUART_DRV_InstallRxCallback(uint32_t...
**         LPUART_DRV_InstallTxCallback   - lpuart_tx_callback_t LPUART_DRV_InstallTxCallback(uint32_t...
**         LPUART_DRV_SendDataBlocking    - lpuart_status_t LPUART_DRV_SendDataBlocking(uint32_t instance,const uint8_t *...
**         LPUART_DRV_SendData            - lpuart_status_t LPUART_DRV_SendData(uint32_t instance,const uint8_t *...
**         LPUART_DRV_GetTransmitStatus   - lpuart_status_t LPUART_DRV_GetTransmitStatus(uint32_t instance,uint32_t *...
**         LPUART_DRV_AbortSendingData    - lpuart_status_t LPUART_DRV_AbortSendingData(uint32_t instance);
**         LPUART_DRV_ReceiveDataBlocking - lpuart_status_t LPUART_DRV_ReceiveDataBlocking(uint32_t instance,uint8_t *...
**         LPUART_DRV_ReceiveData         - lpuart_status_t LPUART_DRV_ReceiveData(uint32_t instance,uint8_t *...
**         LPUART_DRV_GetReceiveStatus    - lpuart_status_t LPUART_DRV_GetReceiveStatus(uint32_t instance,uint32_t *...
**         LPUART_DRV_AbortReceivingData  - lpuart_status_t LPUART_DRV_AbortReceivingData(uint32_t instance);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file lpuartUblox.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup lpuartUblox_module lpuartUblox module documentation
**  @{
*/         
#ifndef __lpuartUblox_H
#define __lpuartUblox_H
/* MODULE lpuartUblox. */
/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"
#include "fsl_lpuart_driver.h"

/*! @brief Device instance number */
#define FSL_LPUARTUBLOX LPUART0_IDX
  
/*! Driver state structure without DMA */
extern lpuart_state_t lpuartUblox_State;
/*! External declaration of Rx buffer */
extern unsigned char ublox_rx[];

/*! @brief Configuration declaration */
extern lpuart_user_config_t lpuartUblox_InitConfig0;
    
#endif
/* ifndef __lpuartUblox_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
