/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : dash_system_boot
**     Processor   : MKL17Z256VFM4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-07-23, 14:39, # CodeGen: 13
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL17Z256FM4
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  DM1 - Differential minus channel 1     : <Automatic>
**                  DM2 - Differential minus channel 2     : <Automatic>
**                  DP1 - Differential plus channel 1      : <Automatic>
**                  DP2 - Differential plus channel 2      : <Automatic>
**                  SE1 - Single-ended channel 1           : <Automatic>
**                  SE2 - Single-ended channel 2           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE11 - Single-ended channel 11         : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  SE23 - Single-ended channel 23         : <Automatic>
**                  SE5a - Single-ended channel 5a         : <Automatic>
**                  SE6a - Single-ended channel 6a         : <Automatic>
**                  SE6b - Single-ended channel 6b         : <Automatic>
**                  SE7b - Single-ended channel 7b         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDDA
**                  Voltage reference low                  : VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN4 - Input 4                          : <Automatic>
**                  OUT - Output                           : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  CLK - Clock                            : <Automatic>
**                  DIO - Data input/output                : <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  OUT - Output pin                       : <Automatic>
**                  Trigger input                          : <Automatic>
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX0
**              Peripheral Type DWT                        : 
**              Peripheral Type FLEXIO                     : 
**                Custom name                              : FLEXIO
**                FLEXIO                                   : 
**                  D0 - Data pin 0                        : <Automatic>
**                  D1 - Data pin 1                        : <Automatic>
**                  D2 - Data pin 2                        : <Automatic>
**                  D3 - Data pin 3                        : <Automatic>
**                  D4 - Data pin 4                        : <Automatic>
**                  D5 - Data pin 5                        : <Automatic>
**                  D6 - Data pin 6                        : <Automatic>
**                  D7 - Data pin 7                        : <Automatic>
**                Bool_FLEXIO                              : yes
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 30                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**                Custom name                              : I2C1
**                I2C1                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C1                                : yes
**              Peripheral Type I2S                        : 
**                Custom name                              : I2S0
**                I2S0                                     : 
**                  MCLK - Master clock                    : <Automatic>
**                  RX_BCLK - RX bit clock                 : <Automatic>
**                  Direction                              : <Automatic>
**                  RX_FS - RX frame sync                  : <Automatic>
**                  Direction                              : <Automatic>
**                  RXD0 - Receive data 0                  : <Automatic>
**                  TX_BCLK - TX bit clock                 : <Automatic>
**                  Direction                              : <Automatic>
**                  TX_FS - TX frame sync                  : <Automatic>
**                  Direction                              : <Automatic>
**                  TXD0 - Transmit data 0                 : <Automatic>
**                Bool_I2S0                                : yes
**              Peripheral Type LCD                        : 
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P5 - Wake-up pin 5                     : <Automatic>
**                  P6 - Wake-up pin 6                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                  P8 - Wake-up pin 8                     : <Automatic>
**                  P9 - Wake-up pin 9                     : <Automatic>
**                  P10 - Wake-up pin 10                   : <Automatic>
**                  P14 - Wake-up pin 14                   : <Automatic>
**                  P15 - Wake-up pin 15                   : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  ALT0 - Pulse counter input 0           : <Automatic>
**                  ALT1 - Pulse counter input 1           : <Automatic>
**                  ALT2 - Pulse counter input 2           : <Automatic>
**                  ALT3 - Pulse counter input 3           : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type LPUART                     : 
**                Custom name                              : LPUART0
**                LPUART0                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART0                             : yes
**                Custom name                              : LPUART1
**                LPUART1                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART1                             : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  External clock/Oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type RFSYS                      : 
**                Custom name                              : RFSYS
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  CLKIN - Clock input                    : <Automatic>
**                  CLKOUT - Oscillator output             : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Trace clock output                     : <Automatic>
**                  ERCLK32K clock output                  : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**                Custom name                              : SPI1
**                SPI1                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI1                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD94
**                  Analog power supply                    : VDDA
**                  Chip ground                            : VSS95
**                  Analog ground                          : VSSA
**                Bool_SUPPLY                              : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH2 - Channel 2                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH3 - Channel 3                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH4 - Channel 4                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH5 - Channel 5                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM1                                : yes
**                Custom name                              : TPM2
**                TPM2                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM2                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART2
**                UART2                                    : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART2                               : yes
**              Peripheral Type USB                        : 
**              Peripheral Type VREF                       : 
**                Custom name                              : VREF
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA: 
**                Custom name, Signal name                 : PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 2: PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL: 
**                Custom name, Signal name                 : PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 3: ADC0_DP1/ADC0_SE1/PTE16/SPI0_SS/UART2_TX/TPM_CLKIN0/FXIO0_D0: 
**                Custom name, Signal name                 : ADC0_DP1/ADC0_SE1/PTE16/SPI0_SS/UART2_TX/TPM_CLKIN0/FXIO0_D0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 4: ADC0_DM1/ADC0_SE5a/PTE17/SPI0_SCK/UART2_RX/TPM_CLKIN1/LPTMR0_ALT3/FXIO0_D1: 
**                Custom name, Signal name                 : ADC0_DM1/ADC0_SE5a/PTE17/SPI0_SCK/UART2_RX/TPM_CLKIN1/LPTMR0_ALT3/FXIO0_D1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 5: ADC0_DP2/ADC0_SE2/PTE18/SPI0_MOSI/I2C0_SDA/SPI0_MISO/FXIO0_D2: 
**                Custom name, Signal name                 : ADC0_DP2/ADC0_SE2/PTE18/SPI0_MOSI/I2C0_SDA/SPI0_MISO/FXIO0_D2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 6: ADC0_DM2/ADC0_SE6a/PTE19/SPI0_MISO/I2C0_SCL/SPI0_MOSI/FXIO0_D3: 
**                Custom name, Signal name                 : ADC0_DM2/ADC0_SE6a/PTE19/SPI0_MISO/I2C0_SCL/SPI0_MOSI/FXIO0_D3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 7: VDDA                                : 
**                Custom name, Signal name                 : VDDA
**              Pin 8: VSSA                                : 
**                Custom name, Signal name                 : VSSA
**              Pin 9: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1: 
**                Custom name, Signal name                 : DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 10: PTA0/TPM0_CH5/SWD_CLK              : 
**                Custom name, Signal name                 : PTA0/TPM0_CH5/SWD_CLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 11: PTA1/LPUART0_RX/TPM2_CH0           : 
**                Custom name, Signal name                 : PTA1/LPUART0_RX/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 12: PTA2/LPUART0_TX/TPM2_CH1           : 
**                Custom name, Signal name                 : PTA2/LPUART0_TX/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 13: PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO     : 
**                Custom name, Signal name                 : PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 14: PTA4/I2C1_SDA/TPM0_CH1/NMI_b       : 
**                Custom name, Signal name                 : PTA4/I2C1_SDA/TPM0_CH1/NMI_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 15: VDD94                              : 
**                Custom name, Signal name                 : VDD94
**              Pin 16: VSS95                              : 
**                Custom name, Signal name                 : VSS95
**              Pin 17: EXTAL0/PTA18/LPUART1_RX/TPM_CLKIN0 : 
**                Custom name, Signal name                 : EXTAL0/PTA18/LPUART1_RX/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 18: XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 19: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : PTA20/RESET_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 20: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0: 
**                Custom name, Signal name                 : ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 21: ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1    : 
**                Custom name, Signal name                 : ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 22: ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0: 
**                Custom name, Signal name                 : ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 23: ADC0_SE11/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS: 
**                Custom name, Signal name                 : ADC0_SE11/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 24: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 25: PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK: 
**                Custom name, Signal name                 : PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 26: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT: 
**                Custom name, Signal name                 : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 27: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK: 
**                Custom name, Signal name                 : CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 28: CMP0_IN1/PTC7/SPI0_MISO/I2S0_RX_FS/SPI0_MOSI: 
**                Custom name, Signal name                 : CMP0_IN1/PTC7/SPI0_MISO/I2S0_RX_FS/SPI0_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 29: PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4: 
**                Custom name, Signal name                 : PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 30: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5: 
**                Custom name, Signal name                 : ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 31: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6: 
**                Custom name, Signal name                 : ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 32: PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7: 
**                Custom name, Signal name                 : PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              HAL fsl_mcglite_hal                        : fsl_mcglite_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

/* MODULE pin_mux. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"



/*FUNCTION**********************************************************************
*
* Function Name : init_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_coredebug_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt7);
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_coredebug_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOC_IDX:                     /* GPIOC_IDX */
      /* Affects PORTC_PCR5 register */
      PORT_HAL_SetPullMode(PORTC,5UL,kPortPullDown);
      PORT_HAL_SetPullCmd(PORTC,5UL,false);
      PORT_HAL_SetMuxMode(PORTC,5UL,kPortMuxAsGpio);
      /* Affects PORTC_PCR6 register */
      PORT_HAL_SetPullCmd(PORTC,6UL,false);
      PORT_HAL_SetMuxMode(PORTC,6UL,kPortMuxAsGpio);
      PORT_HAL_SetPullMode(PORTC,6UL,kPortPullUp);
      /* Affects PORTC_PCR7 register */
      PORT_HAL_SetMuxMode(PORTC,7UL,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTC,7UL,kPortSlowSlewRate);
      break;
    case GPIOD_IDX:                     /* GPIOD_IDX */
      /* Affects PORTD_PCR4 register */
      PORT_HAL_SetMuxMode(PORTD,4UL,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTD,4UL,kPortSlowSlewRate);
      break;
    case GPIOE_IDX:                     /* GPIOE_IDX */
      /* Affects PORTE_PCR16 register */
      PORT_HAL_SetMuxMode(PORTE,16UL,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTE,16UL,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOC_IDX:                     /* GPIOC_IDX */
      PORT_HAL_SetMuxMode(PORTC,5UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTC,6UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTC,7UL,kPortPinDisabled);
      break;
    case GPIOD_IDX:                     /* GPIOD_IDX */
      PORT_HAL_SetMuxMode(PORTD,4UL,kPortPinDisabled);
      break;
    case GPIOE_IDX:                     /* GPIOE_IDX */
      PORT_HAL_SetMuxMode(PORTE,16UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : init_i2c_pins
* Description   : I2C method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_i2c_pins(uint32_t instance)
{
  switch(instance) {    
    case I2C0_IDX:                      /* I2C0_IDX */
      /* Affects PORTB_PCR0 register */
      PORT_HAL_SetMuxMode(PORTB,0UL,kPortMuxAlt2);
      /* Affects PORTB_PCR1 register */
      PORT_HAL_SetMuxMode(PORTB,1UL,kPortMuxAlt2);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_i2c_pins
* Description   : I2C method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_i2c_pins(uint32_t instance)
{
  switch(instance) {    
    case I2C0_IDX:                      /* I2C0_IDX */
      PORT_HAL_SetMuxMode(PORTB,0UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTB,1UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}

/*FUNCTION**********************************************************************
*
* Function Name : init_llwu_pins
* Description   : LLWU method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_llwu_pins(uint32_t instance)
{
  /* Affects PORTC_PCR5 register */
  PORT_HAL_SetPullMode(PORTC,5UL,kPortPullDown);
  PORT_HAL_SetPullCmd(PORTC,5UL,false);
  PORT_HAL_SetMuxMode(PORTC,5UL,kPortMuxAsGpio);
  /* Affects PORTC_PCR6 register */
  PORT_HAL_SetPullCmd(PORTC,6UL,false);
  PORT_HAL_SetMuxMode(PORTC,6UL,kPortMuxAsGpio);
  PORT_HAL_SetPullMode(PORTC,6UL,kPortPullUp);
  /* Affects PORTD_PCR4 register */
  PORT_HAL_SetMuxMode(PORTD,4UL,kPortMuxAsGpio);
  PORT_HAL_SetSlewRateMode(PORTD,4UL,kPortSlowSlewRate);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_llwu_pins
* Description   : LLWU method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_llwu_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC,5UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTC,6UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTD,4UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_lpuart_pins
* Description   : LPUART method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_lpuart_pins(uint32_t instance)
{
  switch(instance) {    
    case LPUART0_IDX:                   /* LPUART0_IDX */
      /* Affects PORTD_PCR6 register */
      PORT_HAL_SetMuxMode(PORTD,6UL,kPortMuxAlt3);
      SIM_HAL_SetLpuartRxSrcMode(SIM,LPUART0_IDX,kSimLpuartRxsrcPin);
      /* Affects PORTD_PCR7 register */
      PORT_HAL_SetMuxMode(PORTD,7UL,kPortMuxAlt3);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_lpuart_pins
* Description   : LPUART method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_lpuart_pins(uint32_t instance)
{
  switch(instance) {    
    case LPUART0_IDX:                   /* LPUART0_IDX */
      PORT_HAL_SetMuxMode(PORTD,6UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTD,7UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}

/*FUNCTION**********************************************************************
*
* Function Name : init_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_osc_pins(uint32_t instance)
{
  /* Affects PORTA_PCR18 register */
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  /* Affects PORTA_PCR19 register */
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_osc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rcm_pins(uint32_t instance)
{
  /* Affects PORTA_PCR20 register */
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rcm_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_spi_pins
* Description   : SPI method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_spi_pins(uint32_t instance)
{
  switch(instance) {    
    case SPI0_IDX:                      /* SPI0_IDX */
      /* Affects PORTE_PCR19 register */
      PORT_HAL_SetMuxMode(PORTE,19UL,kPortMuxAlt2);
      /* Affects PORTE_PCR18 register */
      PORT_HAL_SetMuxMode(PORTE,18UL,kPortMuxAlt2);
      /* Affects PORTE_PCR17 register */
      PORT_HAL_SetMuxMode(PORTE,17UL,kPortMuxAlt2);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_spi_pins
* Description   : SPI method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_spi_pins(uint32_t instance)
{
  switch(instance) {    
    case SPI0_IDX:                      /* SPI0_IDX */
      PORT_HAL_SetMuxMode(PORTE,19UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTE,18UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTE,17UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}


/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
